// <auto-generated />
namespace Pomodoro_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class TagNullableInPomodoro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TagNullableInPomodoro));
        
        string IMigrationMetadata.Id
        {
            get { return "202002091422231_TagNullableInPomodoro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
